name: 'iceberg_example'
version: '1.0.0'
config-version: 2

# Esta configuração define qual "perfil" o dbt usa para este projeto.
profile: 'iceberg_example'

# Estas configurações especificam onde o dbt deve procurar diferentes tipos de arquivos.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # diretório que armazenará os arquivos SQL compilados
clean-targets:         # diretórios a serem removidos pelo comando `dbt clean`
  - "target"
  - "dbt_packages"

# Configurando modelos
models:
  iceberg_example:
    # Configuração indicada por + e se aplica a todos os arquivos sob models/
    +materialized: table
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
