version: 2

models:
  - name: stg_products
    description: "Staged product data from the raw products table"
    columns:
      - name: product_id
        description: "The primary key for products"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "The name of the product"
        tests:
          - not_null
      - name: category
        description: "The category of the product"
        tests:
          - not_null
      - name: price
        description: "The price of the product"
        tests:
          - not_null
      - name: created_date
        description: "The date the product was created"
        tests:
          - not_null

  - name: stg_sales
    description: "Staged sales data from the raw sales table"
    columns:
      - name: sale_id
        description: "The primary key for sales"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Foreign key to the products table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        description: "The quantity of products sold"
        tests:
          - not_null
      - name: total_amount
        description: "The total amount of the sale"
        tests:
          - not_null
      - name: sale_date
        description: "The date of the sale"
        tests:
          - not_null